{% set version = "0.2.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-poorman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poorman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poorman/poorman_{{ version }}.tar.gz
  sha256: 089418293cdfde3b46bf53e891a3a8ad924d953a1a7e5ae981de54ebde62b4aa

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('poorman')"           # [not win]
    - "\"%R%\" -e \"library('poorman')\""  # [win]

about:
  home: https://nathaneastwood.github.io/poorman/, https://github.com/nathaneastwood/poorman
  license: MIT
  summary: A replication of key functionality from 'dplyr' and the wider 'tidyverse' using only 'base'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
